nipy/PySurfer

- surfer/utils.py
The save_movie() function calls ffmpeg with the -c argument which breaks very old versions of ffmpeg such as versions which can be found on old installations of RHEL/CentOS. This PR allows the omission of the -c argument when the codec kwarg is None.
> allow codec to be none for old versions of ffmpeg

- examples/plot_morphometry.py
- examples/plot_probabilistic_label.py
- examples/plot_topographic_contours.py
- surfer/viz.py
GH-#115 removed surfer.io.read_label but did not change the example
that was referencing it. I'm surprised that got through Travis--
does Travis not build the docs?
While fixing this I also noticed a couple of things that had gotten
out of date and fixed an oversight from the config file removal.
> Fix errors that were crashing doc build

- surfer/viz.py
I noticed that `save_movie()` was creating movies slightly shorter than the desired length -- a 6 second movie would become a 5.8 seconds movie, for instance.
I think this is primarily an issue in ffmpeg which would be almost impossible to solve, but I also noticed a minor floating point instability in the calculation of the number of samples in my data.
> Fix sample floatingpoint offby1

- examples/plot_meg_inverse_solution.py
- surfer/viz.py
This should solve the problem of displaying time in ms while representing it in seconds (which is assumed by `Brain.save_movie()` when determining time dilation). To display in ms use `time_label=lambda x: '%s ms' % int(round(x))`.
> ENH Brain:  allow time_label to be function

- examples/save_movie.py
- surfer/viz.py
Mayavi's default bahavior is to change the text size when the number of characters changes, which looks  strange in a movie (see [before](https://www.dropbox.com/s/j551izzp9o405d9/example_before.mov?dl=0)). This PR tries to fix this tentatively by using a constant font size and right-aligning the label (see [after](https://www.dropbox.com/s/9xjjwc7gj10yswp/example_after.mov?dl=0)). I don't know how much of this should be exposed in `Brain.add_data()`, maybe at least the font size?
> ENH:  Time-label consistency over time

- surfer/viz.py
np.arange() sometimes returns values larger than `stop` due to floating 
point round-off, which becomes relevant with large `time_dilation`
values.
I hope that's the last fix for determining movie times :)
> FIX Brain.save_movie():  prevent greater than possible frame times

- surfer/viz.py
The automatic offset creates a problem with my program which uses the vertex coordinates for a complicated algorithm to snap subcortical locations to optimally selected surface vertices and then plots the results. Easiest fix is to allow the user to disable this feature.
> Allow brain without x offset

- surfer/io.py
This prevents trying to create a key, value pair from a line that can't be split on `=` when reading output from `env`.
Closes #144.
> BF: env can print lines without "="

- .travis.yml
- examples/plot_meg_inverse_solution.py
- setup.py
- surfer/io.py
- surfer/viz.py
Brings PySurfer py3k support. No CI support yet because Anaconda packages don't exist yet. But tests pass on my system with Mayavi dev and VTK 7.0.
Closes #143.
> MRG: Py3k support

- surfer/viz.py
Following up on https://github.com/nipy/PySurfer/pull/154
`imageio` parameters: http://imageio.readthedocs.io/en/latest/format_ffmpeg.html#parameters-for-saving
Probably the most sense would make to provide access to all of `imageio`'s options. I've saved a couple of movies and `imageio` seems to have sensible defaults (variable bitrate, hence I removed our fixed bitrate default). We could keep the existing keyword arguments so we don't break code that used positional arguments. Are there better alternatives? I am not sure how to document in case we just include a `**kwargs` in the signature. Should the documentation just include a link to `imageio`'s documentation?
> WIP:  adapt Brain.save_movie() API for imageio

- surfer/tests/test_viz.py
- surfer/viz.py
I sometimes get an issue where the first `screenshot()` is returned at a different resolution (traceback below). If this is not just my system then this PR would fix that.
```
In [6]: brain.save_movie('R2262-loosetttt.mov', time_dilation=.004)
WARNING:root:IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (739, 800) to (752, 800) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to None (risking incompatibility). You may also see a FFMPEG warning concerning speedloss due to data not being aligned.
---------------------------------------------------------------------------
ValueError                                Traceback (most …
```
> [MRG] FIX:  make screenshot() before starting movie

- examples/plot_meg_inverse_solution.py
- surfer/tests/test_viz.py
- surfer/viz.py
Following up on https://github.com/mne-tools/mne-python/pull/3375 CC @jaeilepp @Eric89GXL
> [MRG] ENH:  Set initial time in Brain.add_data() 

- CHANGES
- bin/pysurfer
- examples/plot_transparent_brain.py
- surfer/_commandline.py
- surfer/tests/test_viz.py
- surfer/viz.py
I have added the option to specify alpha transparency for Brain binarized curvature rendering. This can be useful when plotting foci in internal structures that are otherwise obscured by the brain surface. I had considered adding an "alpha" keyword to the Brain interface, but opted instead to allow for alpha transparency to be specified in the cortex keyword. I've implemented the chance in a way that should ensure backward compatibility with code specifying the cortex keyword as a 4-tuple or string (in these cases alpha defaults to 1.0). Using a new alpha transparency keyword for the Brain constructor might make this feature more accessible and I'm happy to change the implementation accordingly if that's preferred.
> NF: added the option to specify alpha transparency for Brain binarized curvature rendering

- surfer/io.py
> Decorate project_volume_data with verbose (closes #160)

- CHANGES
- surfer/tests/test_viz.py
- surfer/viz.py
To allow saving image with alpha channel
> [MRG] API: expose screenshot params in save_image() 

- surfer/io.py
This should make it easier to debug problems when using `project_volume_data`. Not sure why we were just printing the command line before (which gets printed anyway).
Closes #171.
> Show stderr when mri_vol2surf fails

- surfer/tests/test_viz.py
- surfer/viz.py
On Mayavi 4.5.0 (conda), I get a ton of warnings due to `traits` during normal usage. This gets rid of most of them.
The only ones left now are of the form:
```
ERROR: In /home/ilan/minonda/conda-bld/work/VTK-6.3.0/Rendering/Core/vtkCoordinate.cxx, line 351
vtkCoordinate (0x6e7a7a0): Request for coordinate transformation without required viewport
```
But I can't suppress those I don't think.
> MRG: Suppress spewed traits warnings

- surfer/tests/test_viz.py
- surfer/viz.py
The option to specify `figure` as int and the type check were in men-python (see https://github.com/mne-tools/mne-python/pull/3375), should they be included in PySurfer?
> [MRG] figure args

- examples/plot_meg_inverse_solution.py
- surfer/tests/test_viz.py
- surfer/viz.py
I've wanted a trackball-style camera in Mayavi for a while and finally figured out how to get it.
> MRG: Add terrain interaction

- surfer/tests/test_viz.py
- surfer/viz.py
Previously `Brain` time-setters and `.add_data(remove_existing=True)` only affected the most recently added data-layer on each hemisphere.
> FIX: showing multiple data layers

- surfer/tests/test_viz.py
- surfer/viz.py
Remove the `hemi` parameter, which was previously unused (even though it forced the user to set it). Labels are not stored by hemisphere, but by their name.
> [MRG] FIX Brain.remove labels()

- .mailmap
- surfer/viz.py
Closes #188
There is an inconsistency where the previous method wanted values in [0, 255] while the current method wants values in [0, 1]. I decided to handle this within each method to otherwise maintain prior API.
I generated the docs on my Ubuntu system and everything looks good. It would  be best to have someone else on a different system verify that the example gallery does not change with this PR.
> Use different interface for setting LUT

- surfer/viz.py
`mlab.view()` does not return parallel_scale (which only becomes apparent when setting the camera to use parallel projection)
> FIX toggle_render:  store camera parallel_scale

- CHANGES
- examples/plot_basics.py
- examples/plot_meg_inverse_solution.py
- examples/plot_parc_values.py
- examples/plot_parcellation.py
- surfer/tests/test_viz.py
- surfer/utils.py
- surfer/viz.py
I often find myself plotting with one surface and then wanting to look at it with another. This implementation is based on keeping track of all the meshes that are added to the brain. I've implemented it for data, labels and annotations, not yet for all other layer types because I wanted to confirm first that there is no better way to implement it. I was wondering whether all the mesh objects could be combined into one somehow (re #177), but it looks like they all need to have a different `scalars` attribute, and I don't see a straightforward way to separate the scalars from the triangular mesh...
> [MRG]: Set surface

- .travis.yml
- appveyor.yml
- make/get_fsaverage.ps1
- surfer/tests/test_utils.py
- surfer/tests/test_viz.py
- surfer/utils.py
- surfer/viz.py
This should fix AppVeyor and make it build the docs (in noplot mode).
> ENH: Add doc build

- surfer/tests/test_viz.py
- surfer/viz.py
Fix for a corner case where multiple data layers are added, and not all of them have a time axis
> FIX Brain.set_data_time_index():  skip data without time axis

- surfer/tests/test_viz.py
- surfer/viz.py
I've been creating annotations programmatically and wanted to plot them without saving them to a file first. The change simply allows providing the output of the file read operation directly, most of the changed lines are just due to indentation.
> ENH:  Add annotation from arrays

- surfer/utils.py
- Allow color-lists with colors including alpha
- Allow specifying color-lists as tuples (which was possible previously, so since tuples are often used interchangeably with lists I am not sure whether you removed this intentionally)
> Colormap as list tweaks

- examples/plot_parc_values.py
#200 reminded me that by switching the parcellation example back to using the aparc, it's necessary to handle undefined vertices.
> Handle undefind vertices in parcellation example

- examples/plot_vector_meg_inverse_solution.py
- surfer/tests/test_viz.py
- surfer/viz.py
Eventually this will let us add vector data like `(n_vertices, 3, n_time)`, which is useful for electrophysiological estimates (e.g., MEG inverse solutions). Right now it doesn't look so good but it at least does not throw an error.
Code adapted from the [MNE PR](https://github.com/mne-tools/mne-python/pull/3842) by @wmvanvliet.
Todo:
> MRG: Add support for vector data in `add_data`

- surfer/viz.py
We get a ton of these messages in MNE because we use `add_data`:
```
Updating smoothing matrix, be patient..
Smoothing matrix creation, step 1
Smoothing matrix creation, step 2
Smoothing matrix creation, step 3
Smoothing matrix creation, step 4
Smoothing matrix creation, step 5
Smoothing matrix creation, step 6
Smoothing matrix creation, step 7
Smoothing matrix creation, step 8
Smoothing matrix creation, step 9
Smoothing matrix creation, step 10
```
This will allow us to pass `verbose=False` to avoid them (this process is quick enough we don't need to be informed of the progress).
> MRG: Add verbose argument

- circle.yml
- doc/Makefile
- examples/plot_meg_inverse_solution.py
- examples/plot_vector_meg_inverse_solution.py
> MRG: Add CircleCI

- surfer/viz.py
@nfoti can you see if this fixes your problem?
This forces a GUI process loop update when calling `_force_render`, which is useful e.g. to deal with the toolbar removal at the beginning. @nfoti found that getting the model-view matrix in a script was different before/after allowing the interpreter to idle, which is a sign that the idle-GUI-loop code was doing something to the display, which shouldn't happen if no interaction has taken place and we are properly forcing rendering changes.
Tests pass locally, let's see if the CIs are happy.
> MRG: Always force GUI updates

- surfer/viz.py
When annotating the brain with a brain atlas, the colors are not always set right:
```python
import surfer
brain = surfer.Brain('fsaverage', hemi='both', surf='inflated')
brain.add_annotation('aparc', borders=False)
```
This has to do with the reordering of `cmap` and the translation of the `ids` vector. This PR fixes it:
> Fix annotation colors

- setup.py
When trying to set up an Anaconda environment using `pip` to simultaneously install `mayavi` and `PySurfer`, I get these errors:
```
Installing collected packages: mne, nibabel, imageio, pysurfer, nitime, nilearn, quantities, neo, termcolor, pytest-sugar, pytest-faulthandler, pydocstyle, sphinx-bootstrap-theme, traits, pyface, traitsui, configobj, apptools, mayavi, sphinx-gallery
Running setup.py install for pysurfer ... error
Complete output from command /home/larsoner/anaconda2/envs/mne/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-45nhe837/pysurfer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3smloy5u-record/install-record.txt …
```
> FIX: Fix setup.py

- examples/plot_meg_inverse_solution.py
- examples/plot_resting_correlations.py
- surfer/utils.py
- surfer/viz.py
When analysing some of my data I came across the issue that I couldn't use a divergent colormap for, e.g., correlations or t-values and at the same time let small values in the middle of the colormap be transparent. So I have adapted Brain.scale_data_colormap such that it can now handle transparency in divergent colormaps properly. Also, I added the option to set the overall alpha-level of the colormap while maintaining transparency of a particular region in the colormap. The usage of these features is demonstrated in examples/plot_resting_correlations.py.
I believe that these changes make it easier to explore suitable visualisations of divergent data and hope that you find them useful!
> MRG+1: allowing transparency in divergent colormaps

- surfer/viz.py
Fixes an error I get when opening a `TimeViewer` complaining about `'center'` missing from the data properties dict.
> BUG: Add 'center' as a data property

- surfer/viz.py
The problem can be seen by using a view in which roll is non-default, for example "ventral", and adding data; before this patch, the view changed after the add_data call.
Also adding a comment to docs to clarify something that confused me the first time I read it.
> [MRG] View persistence

- surfer/viz.py
When setting different DPI in `rcParams` saved images are wrongly scaled (see below). I suspect it's because unlike matplotlib's `imsave`, `PySurfer`  does not use `dpi` when saving the image. This PR fixes this.
> FIX save_image() dpi

- surfer/tests/test_viz.py
Avoid creating files in the repository during testing.
> TEST:  use pytest tmpdir fixture

- surfer/viz.py
Adds `offscreen='auto'` as the default, which will use the `mlab.options.offscreen` value.
> MRG: Add auto offscreen mode

- surfer/viz.py
Closes #250.
Works around a `nibabel` bug and actually should slightly improve the `borders` functionality by setting the transparent color better (to the brain background with alpha 0 instead of black with alpha 0, which helps with transitions).
@fliem can you see if this fixes your problem?
> FIX: annotations and bgcolor

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- setup.cfg
- surfer/tests/test_utils.py
- surfer/tests/test_viz.py
- surfer/utils.py
- surfer/viz.py
Fixes a bug from #245 that showed up when `w != h` as values ended up swapped.
> MRG: width/height in offscreen mode

- doc/install.rst
- surfer/viz.py
Mayavi can render things inside a jupyter notebook as either PNG or X3D.
This functionality can be enabled with `mlab.init_notebook()`.
This PR adds an `_ipython_display_` hook to the `Brain` class that
renders the brain accordgin to the Mayavi notebook integration settings.
This means interactive PySurfer brains in Binder are now possible!
https://mybinder.org/v2/gh/wmvanvliet/SNL_workshop_2019/master?filepath=pysurfer_demo.ipynb
> Integrate better with Jupyter notebook

- .circleci/config.yml
- .travis.yml
- doc/Makefile
- doc/conf.py
- doc/documentation/command_line.rst
- examples/plot_label.py
- examples/plot_probabilistic_label.py
In MNE we recently introduced a `fsaverage` dataset fetcher. Might as well use it here. It should help with #269.
> MAINT: Update fsaverage

- surfer/viz.py
I was having an issue where one label in an annotation would mistakenly be colored bright blue. e.g. this is an incorrect rending of the Yeo2011_7Networks_N1000 annot included with Freesurfer:
The issue seems to be this. [`add_annotation`](https://github.com/nipy/PySurfer/blob/master/surfer/viz.py#L3296) is setting the colors by calling `surf.module_manager.scalar_lut_manager.load_lut_from_list`. This keeps the lookup table at 255 colors and sets the first `n` colors where `n` is the length of the list you pass in. So what's happening is the "wrong" label is the largest ID in the annotation, and it is being colored in with the next color, which is blue (for a relatively small annotation). Why is that happening? It's not exactly clear. I don't see anything obviously wrong with the code we …
> Set annotation LUT directly

- surfer/tests/test_viz.py
- surfer/viz.py
A small enhancement that makes it easy to show the borders between annotation labels in a single color. This makes less distracting figures in cases where you want to overlay an annotation on a statistical map and either know what each parcel represents or don't precisely care.
e.g.
```python
from surfer import Brain
b = Brain("fsaverage", "lh", "inflated")
b.add_annotation("aparc", color="dodgerblue")
```
> ENH: Allow painting all annotation vertices in a single color

- .gitignore
- CHANGES
- doc/changes.rst
- doc/index.rst
- examples/plot_meg_inverse_solution.py
- surfer/tests/test_utils.py
- surfer/utils.py
- surfer/viz.py
Allows doing `smoothing_steps='nearest'` so you can see the patches of cortex like (not the most relevant example but gives the idea):
> ENH: Add option to smooth to nearest

- surfer/viz.py
This should fix a bug @drammock hit where memory consumption crept up with multiple `fig` use and `mlab.options.offscreen=True`. Basically we should make sure we close the figures we create, since the offscreen ones can stay open and consume memory.
> BUG: Properly clean up on del

- surfer/io.py
- surfer/tests/test_viz.py
- surfer/viz.py
Under some circumstances #279 could lead to ugly exits like:
```
$ python -u ~/Desktop/brain.py 
Exception ignored in: <function Brain.__del__ at 0x7fd4dc0ac820>
Traceback (most recent call last):
File "/home/larsoner/python/PySurfer/surfer/viz.py", line 2306, in __del__
File "/home/larsoner/python/PySurfer/surfer/viz.py", line 2296, in close
File "/home/larsoner/python/mayavi/mayavi/tools/figure.py", line 185, in close
File "/home/larsoner/.local/lib/python3.8/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
File "/home/larsoner/python/mayavi/mayavi/core/engine.py", line 491, in close_scene
File "/home/larsoner/python/mayavi/tvtk/pyface/tvtk_scene.py", line 355, in close
File "/home/larsoner/.local/lib/python3.8/site-packages/traits/trait_notifiers.py", line 400, in …
```
> MRG, FIX: Safer exit

- surfer/viz.py
Ok. More digging and potential solutions.
An undocumented workaround for various rendering bugs in some graphics drivers is to hack your local [`site-packages/vtkmodules/qt/__init__.py`](https://github.com/Kitware/VTK/blob/master/Wrapping/Python/vtkmodules/qt/__init__.py#L33-L37) file and make this change:
```python
QVTKRWIBase = "QGLWidget"  # Changed from "QWidget" -> "QGLWidget"
```
Code relying on `vtkmodules`, such as Mayavi and pyvista, will [check the `QVTKRWIBase` variable and try to do the right thing accordingly](https://github.com/enthought/mayavi/blob/master/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py#L61-L66). Unfortunately, for some reason, it decided to do this:
```python
if PyQtImpl == "PyQt5":
if QVTKRWIBase == "QGLWidget":
try:
from PyQt5.QtWidgets import …
```
> Fix rendering of overlay on some graphic chipsets.

- setup.cfg
- surfer/tests/test_viz.py
- surfer/viz.py
Closes #281
On `master` the [snippet from #281](https://github.com/nipy/PySurfer/issues/281#issuecomment-576281140) gives:
And on this PR:
@mwaskom feel free to look/test/merge if you're happy.
> MRG, FIX: Fix bug with scale_data_colormap

- azure-pipelines.yml
- surfer/tests/test_viz.py
- surfer/viz.py
Over at MNE [we have been getting failures](https://github.com/mne-tools/mne-python/pull/7294) that seem to be triggered by the GUI stuff we do when `__del__` is called. This hopefully avoids the problem.
WIP until we can do some runs in MNE to see if it makes the problem go away.
> MRG, FIX: Remove force render

- .travis.yml
- surfer/io.py
- surfer/utils.py
- surfer/viz.py
When processing things in a loop I get spammed by a lot of:
```
colormap sequential: [0.00e+00, 9.68e-01, 1.94e+00] (transparent)
colormap sequential: [0.00e+00, 9.68e-01, 1.94e+00] (transparent)
colormap sequential: [0.00e+00, 9.68e-01, 1.94e+00] (transparent)
colormap sequential: [0.00e+00, 9.68e-01, 1.94e+00] (transparent)
```
I don't think this is very useful for users in general, so by default we probably shouldn't log it.
> STY: Dont log info messages by default

- .travis.yml
- doc/install.rst
- setup.py
Let's see if it works.
Also bumps minimum Python to 3.6.
> ENH: Move up to 3.8

- appveyor.yml
- azure-pipelines.yml
- surfer/viz.py
FXAA can be problematic with OSMESA, give users a way to disable it.
> ENH: Add FXAA option

- .circleci/config.yml
- .travis.yml
- surfer/viz.py
We can avoid a lot of gymnastics having to do with maximum magnitudes and even scalars by setting the `scale_mode='vector'` in the `quiver3d` call.
> MRG, MAINT: Simpler vector params

- README.md
the link was broken due to github policy change. 
https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/
> github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021
