nipy/PySurfer

surfer/viz.py

- Allow for a custom colormap
- Allow for custom min/max
- Plot bivariate measures (curv and sulc) with the midpoint at 0
- Compute the min and max of the colormap robustly
- Allow morphometry colorbar to be optional

Add a few enhancements to morphometry plotting

---

CHANGES
surfer/viz.py

- Make the colorbar optional
- Make removal of existing contour overlays optional

Add some flexibiltiy to contour overlays

---

surfer/utils.py

Sorry there was a slight bug with a style correction that was made here.

fix severe bug with codec being None

---

surfer/utils.py
surfer/viz.py

I noticed the movies I was creating from pysurfer were sometimes very low quality.

add bitrate option to ffmpeg call

---

surfer/io.py

Addresses #102.
Check `os.environ` and run `$FREESURFER_HOME/FreeSurferEnv.sh` if not the most recent script to edit the `PATH`. Parse the resulting environment and pass to `mri_vol2surf`, avoiding modifying the base process environment.

Check environment and run FreeSurferEnv.sh if necessary

---

README.md
doc/index.rst
doc/links_names.txt

Point to new neuroimaging mailing list

DOC: change location of mailing list

---

surfer/viz.py

changed import line in make_montage to resolve #150

fix import Image in make_montage

---

.travis.yml
appveyor.yml
doc/install.rst
setup.py
surfer/tests/test_viz.py
surfer/utils.py
surfer/viz.py

Picking up an old suggestion from @Eric89GXL this uses [imageio](http://imageio.readthedocs.io/en/latest/index.html) for saving movies. Imageio downlaods and manages the FFMPEG binary automatically so this would provide considerable simplification.

[WIP] Imageio

---

surfer/tests/test_viz.py
surfer/viz.py

@agramfort this fixes https://github.com/mne-tools/mne-python/pull/3590 for me. It's not an old numpy but a new numpy problem (I'm running 1.2-dev and get this error).

MRG: Fix for empty case

---

CHANGES

Re #165, updating changes. `setup.py` already has Python 3 classifiers. Is #139 substantial enough to include a note?

DOC changes

---

.travis.yml
examples/plot_meg_inverse_solution.py
surfer/tests/test_viz.py

Let's see if this works. From:
https://github.com/ContinuumIO/anaconda-issues/issues/1365

FIX: Fix Travis

---

surfer/viz.py

MRG: Dont try/except save

---

MANIFEST.in

This is encouraged by conda-forge (https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L52)

add MANIFEST.in to include LICENSE in sdist

---

surfer/tests/test_viz.py
surfer/viz.py

Bug introduced in https://github.com/nipy/PySurfer/pull/191

FIX:  negative overlay

---

appveyor.yml
doc/_static/navy.css
doc/conf.py
examples/plot_vector_meg_inverse_solution.py
surfer/tests/test_viz.py
surfer/viz.py

Closes #199.
Todo:
~~Still need to make sure the rest of the issues in there are addressed.~~ In the meantime, the first commit fixes the vector example build (wouldn't work on OSX -- figures are closed at the end of each SG section).

MRG: Improve doc

---

.travis.yml
appveyor.yml
codecov.yml
setup.cfg
surfer/tests/test_viz.py
surfer/viz.py

A small tweak to ensure we check that `fmin < fmid < fmax`.

MRG: Check limit monotonicity

---

.travis.yml
appveyor.yml
doc/install.rst
environment.yml
surfer/tests/test_viz.py
surfer/utils.py
surfer/viz.py

Closes #209.
@mwaskom I used your approach but left the figure-generation private for now. Feel free to make a follow-up PR to make it public with proper documentation, etc.

MRG: Fix imsave

---

.travis.yml

This will hopefully fix our OSX timeouts.

FIX: Fix OSX

---

surfer/viz.py

Closes #236.
@ktavabi can you confirm this fixes the bug for you?

MRG: Fix roll setting

---

environment.yml

Will merge if they come back happy.

FIX: Update CIs

---

examples/plot_custom_colors.py
examples/plot_custom_colours.py

Hi @larsoner,
I have (finally - I'm sorry) put together a draft of the script that allows for plotting custom rgba values. Any feedback is appreciated!
Thanks,
Laura
Closes #228

ADD: first draft of plot_custom_colours script

---

surfer/tests/test_viz.py
surfer/viz.py

Seemed like it was missing and simple enough to add.

[MRG] ADD:  Brain.remove_foci()

---

doc/_templates/class_noinherited.rst
doc/conf.py
doc/python_reference.rst
surfer/viz.py

@OlehKSS noticed that `TimeViewer` was not in the API docs. This adds it.

MRG: Add TimeViewer to docs
